baseURL: https://www.aurelienschiltz.dev
languageCode: fr-fr
defaultContentLanguage: fr
title: Aurelien SCHILTZ - Developpeur Web
theme: cupper-hugo-theme
googleAnalytics: UA-123456789-1
disqusShortname: yourdiscussshortname
enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: An accessibility-friendly Hugo theme, ported from the [original Cupper](https://github.com/ThePacielloGroup/cupper) project.
  homeMetaContent: An accessibility-friendly Hugo theme, ported from the original Cupper project.
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [Netlify](https://www.netlify.com/).
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: true

menu:
  nav:
    - name: Accueil
      url: /
      weight: 1
    - name: Articles
      url: /post/
      weight: 2
    - name: CV
      url: /about/
      weight: 3
