baseURL: https://www.aurelienschiltz.dev
languageCode: fr-fr
defaultContentLanguage: fr
title: Aurélien SCHILTZ - Développeur Web
theme: hugo-resume
googleAnalytics: UA-123456789-1
disqusShortname: yourdiscussshortname
enableGitInfo: true

params.email: "aurelienschiltz@gmail.com"


taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99
